version: 1.0.0.{build}
platform: Any CPU
os: Visual Studio 2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: 
before_build:
- ps: "if($env:APPVEYOR_REPO_BRANCH -eq "master"){if($env:APPVEYOR_REPO_TAG -eq $true){$env:CONFIGURATION = "Release" Write-Host "Switch to Release configuration"} else{$env:CONFIGURATION = "Debug" Write-Host "Switch to Debug configuration"}}"
build:
  verbosity: normal
after_build:
- ps: "if($env:APPVEYOR_REPO_TAG -eq $true){ \nappveyor PushArtifact ..\\downloadsmanager\\DownloadsManager\\DownloadsManager\\bin\\Release\\setup.exe \n}"
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: DownloadsManager Release-$(APPVEYOR_REPO_TAG_NAME)
  description: New $(APPVEYOR_REPO_TAG_NAME) version of DownloadManager
  auth_token:
    secure: 4GIUl2Adrmz1NcTRLgPccHqgaRmeduFJwGrOo2ZX6CFkwarHWFMugEq1604RUzS6
  artifact: setup.exe
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
on_success:
- ps: 